version: "3"

services:

  todotests:
    # build: todotests/
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
  
  todofront:
    # build: todofrontend/
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
  
  todoback:
    # build: todobackend/
    image: todobackend
    ports:
      - 3001:3001
  